export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const SAVE_TERM = 'SAVE_TERM';
export const TOGGLE_SEARCH_BY = 'TOGGLE_SEARCH_BY';
export const TOGGLE_SORT_BY = 'TOGGLE_SORT_BY';
export const TOGGLE_SORT_ORDER = 'TOGGLE_SORT_ORDER';